services:
  - type: web
    name: sns-chat-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
