services:
  - type: web
    name: sns-chat-analyzer
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
